---
title: "Bayesian Dynamic Generalized Exponential Growth Model: Examples"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Bayesian Dynamic Generalized Exponential Growth Model: Examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align = "center",
  fig.width = 10,
  fig.height = 6)
options(digits = 4)
```

```{r setup, message=FALSE}
library(RBATS)
library(dplyr)
library(ggplot2)
library(cowplot)
theme_set(
  theme_cowplot(font_size = 16, font_family = "Palatino") +
    background_grid()
)
```

## Simulated example

```{r plot-sim-data}
set.seed(6669)
n <- 60
theta_1 <- 50
theta_2 <- 45
theta_3 <- 0.95
t <- seq.int(1, n)
mu <- theta_1 - theta_2 * theta_3^t
y <- mu + rnorm(n, sd = 0.05 * mu)
plot(y~t)
lines(mu, lwd = 2, col = "blue")
```

```{r fit-sim-data-example}
# Define the model
(model_object <- dgegm(lambda = -1, discount_factors = c(0.90, 0.90, 0.95),
                      variance_law = list(type = "poisson")))
# Fitting the model
(fitted_model <- fit(object = model_object, y = y))
logLik(fitted_model)
```

```{r fit-sim-data}
lambdas <- c(-1, -1/2, 0, 1/2, 1)
lt_fits <- lapply(lambdas, function(l) {
  cat(l, "\n")
  model_object <- dgegm(lambda = l, discount_factors = c(0.90, 0.90, 0.95),
        variance_law = list(type = "poisson"))
  fit(object = model_object, y = y)
})
```

```{r metrics-sim-data}
compute_metrics <- function(x) {
  y <- x$y
  f <- x$data_predictive_filter$mean
  data.frame(lambda = x$lambda, lpl = logLik(x), rmse = sqrt(mean((y - f)^2)),
             mape = 100 * mean(abs((y - f) / y)))
}
do.call("rbind", lapply(lt_fits, compute_metrics))
```

```{r plot-fit-sim-data}
get_data_predictive <- function(x) {
  tmp <- x$data_predictive_filter
  tmp$lambda <- x$lambda
  tmp
}
df_predictive <- do.call("rbind", lapply(lt_fits, get_data_predictive))
ggplot(df_predictive, aes(x = t, y = y)) +
  geom_point(size = 2) +
  geom_line(aes(y = mean, col = factor(lambda))) +
  colorspace::scale_color_discrete_diverging() +
  labs(col = expression(lambda)) +
  theme(legend.position = "top")
df_predictive %>% 
  group_by(lambda) %>% 
  slice(-(1:10)) %>%
  ungroup() %>% 
  mutate(lambda = paste0(expression(lambda), "==", lambda)) %>% 
  ggplot(aes(x = t, y = y)) +
  facet_wrap(~lambda, labeller = label_parsed) +
  geom_point(size = 2) +
  geom_line(aes(y = mean), col = "blue") +
  geom_line(aes(y = ci_lower), col = "blue", linetype = "dashed") +
  geom_line(aes(y = ci_upper), col = "blue", linetype = "dashed")
```


```{r plot-fit-parms-sim-data}
get_data_posterior <- function(x) {
  tmp <- x$data_posterior_filter
  tmp$lambda <- x$lambda
  tmp
}
df_posterior <- do.call("rbind", lapply(lt_fits[1L], get_data_posterior))
ggplot(df_posterior, aes(x = t, y = mean)) +
  facet_wrap(~parameter, ncol = 1, scales = "free_y") +
  geom_line()
```

## Aids Brazil


```{r plot-aids-data}
data("aids_brasil", package = "RBATS")
ggplot(aids_brasil, aes(x = time, y = cases)) +
  geom_point(size = 2) +
  scale_x_date(breaks = scales::pretty_breaks(8), date_labels = "%b/%Y")
```

```{r fit-aids-data}
lambdas <- c(-1, 0, 1)
law_type <- c("identity", "poisson")
df_parms <- expand.grid(lambda = lambdas, law_type = law_type, p = 2,
                        stringsAsFactors = FALSE)
lt_fits <- lapply(seq_len(nrow(df_parms)), function(j) {
  df_cur <- df_parms[j, ]
  cat("lambda = ", df_cur$lambda, "variance law = ", df_cur$law_type, "\n")
  model_object <- dgegm(lambda = df_cur$lambda, discount_factors = c(0.90, 0.90, 0.95),
        variance_law = list(type = df_cur$law_type, p = df_cur$p))
  fit(object = model_object, y = aids_brasil$cases)
})
names(lt_fits) <- seq_len(length(lt_fits))
```

```{r metrics-aids-data}
compute_metrics <- function(x) {
  y <- x$y
  f <- x$data_predictive_filter$mean
  data.frame(
    lambda = x$lambda, variance_law = x$variance_law$type, 
    lpl = logLik(x), rmse = sqrt(mean((y - f)^2)), mape = 100 * mean(abs((y - f) / y)))
}
df_metrics <- do.call("rbind", lapply(lt_fits, compute_metrics))
df_metrics <- df_metrics[!is.infinite(df_metrics$lpl), ]
df_metrics <- df_metrics[do.call(order, as.list(df_metrics["lpl"])),]
df_metrics
```

```{r plot-fit-aids-data}
get_data_predictive <- function(x) {
  tmp <- x$data_predictive_filter
  tmp$lambda <- x$lambda
  tmp$variance_law <- x$variance_law$type
  tmp$time <- aids_brasil$time
  tmp
}
chosen_id <- rownames(head(df_metrics, 4))
df_predictive <- do.call("rbind", lapply(lt_fits[chosen_id], get_data_predictive))
df_predictive$model_id <- paste0("lambda = ", df_predictive$lambda,
                                 "; variance law ", df_predictive$variance_law)
ggplot(df_predictive, aes(x = time, y = y)) +
  geom_point(size = 2) +
  facet_wrap(~model_id) +
  geom_point(size = 2) +
  geom_line(aes(y = mean), col = "blue") +
  scale_x_date(breaks = scales::pretty_breaks(8), date_labels = "%b/%y")
```

```{r plot-fit-wrap-aids-data}
df_predictive %>% 
  group_by(model_id) %>%
  slice(-(1:10)) %>% 
  ungroup() %>%
  ggplot(aes(x = time, y = y)) +
  facet_wrap(~model_id, scales = "free") +
  geom_point(size = 2) +
  geom_line(aes(y = mean), col = "blue", size = 0.8) +
  geom_line(aes(y = ci_lower), col = "blue", linetype = "dashed") +
  geom_line(aes(y = ci_upper), col = "blue", linetype = "dashed") +
  scale_x_date(breaks = scales::pretty_breaks(8), date_labels = "%b/%y")
```

```{r plot-fit-parms-aids-data}
get_data_posterior <- function(x) {
  tmp <- x$data_posterior_filter
  tmp$lambda <- x$lambda
  tmp$variance_law <- x$variance_law$type
  tmp$time <- aids_brasil$time
  tmp
}
df_posterior <- do.call("rbind", lapply(lt_fits[chosen_id[1L]], get_data_posterior))
df_posterior$model_id <- paste0("lambda = ", df_posterior$lambda,
                                "; variance law ", df_posterior$variance_law)
ggplot(df_posterior, aes(x = time, y = mean)) +
  facet_wrap(~parameter, ncol = 1, scales = "free_y") +
  geom_line() +
  # geom_line(aes(y = ci_lower), linetype = "dashed") +
  # geom_line(aes(y = ci_upper), linetype = "dashed") +
  scale_x_date(breaks = scales::pretty_breaks(8), date_labels = "%b/%y")
```


