// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// update_dlm
Rcpp::List update_dlm(const double y, const arma::vec F, const arma::mat G, const arma::mat D, arma::vec a, arma::mat R, const double n, const double s, const double df_variance);
RcppExport SEXP _RBATS_update_dlm(SEXP ySEXP, SEXP FSEXP, SEXP GSEXP, SEXP DSEXP, SEXP aSEXP, SEXP RSEXP, SEXP nSEXP, SEXP sSEXP, SEXP df_varianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type F(FSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< const double >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type df_variance(df_varianceSEXP);
    rcpp_result_gen = Rcpp::wrap(update_dlm(y, F, G, D, a, R, n, s, df_variance));
    return rcpp_result_gen;
END_RCPP
}
// forward_filter_dlm
Rcpp::List forward_filter_dlm(arma::vec const y, arma::vec const F, arma::mat const G, arma::mat const D, arma::vec a, arma::mat R, double n, double s, const double df_variance);
RcppExport SEXP _RBATS_forward_filter_dlm(SEXP ySEXP, SEXP FSEXP, SEXP GSEXP, SEXP DSEXP, SEXP aSEXP, SEXP RSEXP, SEXP nSEXP, SEXP sSEXP, SEXP df_varianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec const >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec const >::type F(FSEXP);
    Rcpp::traits::input_parameter< arma::mat const >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::mat const >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type df_variance(df_varianceSEXP);
    rcpp_result_gen = Rcpp::wrap(forward_filter_dlm(y, F, G, D, a, R, n, s, df_variance));
    return rcpp_result_gen;
END_RCPP
}
// forward_filter_dlm_X
Rcpp::List forward_filter_dlm_X(arma::vec const y, arma::vec const F, arma::mat const X, arma::mat const G, arma::mat const D, arma::vec a, arma::mat R, double n, double s, const double df_variance);
RcppExport SEXP _RBATS_forward_filter_dlm_X(SEXP ySEXP, SEXP FSEXP, SEXP XSEXP, SEXP GSEXP, SEXP DSEXP, SEXP aSEXP, SEXP RSEXP, SEXP nSEXP, SEXP sSEXP, SEXP df_varianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec const >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec const >::type F(FSEXP);
    Rcpp::traits::input_parameter< arma::mat const >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat const >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::mat const >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type df_variance(df_varianceSEXP);
    rcpp_result_gen = Rcpp::wrap(forward_filter_dlm_X(y, F, X, G, D, a, R, n, s, df_variance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RBATS_update_dlm", (DL_FUNC) &_RBATS_update_dlm, 9},
    {"_RBATS_forward_filter_dlm", (DL_FUNC) &_RBATS_forward_filter_dlm, 9},
    {"_RBATS_forward_filter_dlm_X", (DL_FUNC) &_RBATS_forward_filter_dlm_X, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_RBATS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
